// <auto-generated />
using AnimalShelterAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterAPI.Migrations
{
    [DbContext(typeof(AnimalShelterAPIContext))]
    [Migration("20230818184645_AddBreedPropertyAndSeedDate")]
    partial class AddBreedPropertyAndSeedDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterAPI.Models.RescueAnimal", b =>
                {
                    b.Property<int>("RescueAnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Adoptable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RescueAnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            RescueAnimalId = 1,
                            Adoptable = true,
                            Age = 4,
                            Breed = "American Longhair",
                            Description = "A linty fluffball.",
                            Name = "Linty",
                            Species = "Feline"
                        },
                        new
                        {
                            RescueAnimalId = 2,
                            Adoptable = true,
                            Age = 2,
                            Breed = "Labrador",
                            Description = "A smelly doggo.",
                            Name = "Smelly",
                            Species = "Canine"
                        },
                        new
                        {
                            RescueAnimalId = 3,
                            Adoptable = true,
                            Age = 1,
                            Breed = "Sphynx",
                            Description = "A smooth bingus.",
                            Name = "Bingus",
                            Species = "Feline"
                        },
                        new
                        {
                            RescueAnimalId = 4,
                            Adoptable = false,
                            Age = 36,
                            Description = "He's gonna be so mad when he sees this, it'll be great",
                            Name = "Greg",
                            Species = "Human"
                        },
                        new
                        {
                            RescueAnimalId = 5,
                            Adoptable = true,
                            Age = 4,
                            Breed = "Beagle",
                            Description = "Professional Dog Detective. Do not remove hat.",
                            Name = "Sheila",
                            Species = "Canine"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
